/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e4e3db',
        'surface-container': '#f0eee6',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#1a4d5a',
        'background': '#fbf9f1',
        'tertiary-container': '#abd6a5',
        'surface-tint': '#864d61',
        'outline': '#837377',
        'secondary-container': '#b7e7f7',
        'pastel-green': '#C1E1C1',
        'tertiary': '#41673f',
        'on-secondary-container': '#3a6977',
        'on-surface': '#1b1c17',
        'on-primary-container': '#7b4458',
        'inverse-primary': '#fab3ca',
        'pastel-yellow': '#FFF5BA',
        'error-container': '#ffdad6',
        'primary-container': '#ffb7ce',
        'inverse-surface': '#30312c',
        'secondary-fixed-dim': '#9ecede',
        'primary': '#864d61',
        'on-error': '#ffffff',
        'ink-blue': '#4A5568',
        'tertiary-fixed': '#c2eebb',
        'tertiary-fixed-dim': '#a7d2a1',
        'on-tertiary-fixed-variant': '#2a4f2a',
        'surface-container-highest': '#e4e3db',
        'on-surface-variant': '#514347',
        'on-background': '#1b1c17',
        'on-secondary': '#ffffff',
        'primary-fixed': '#ffd9e3',
        'on-primary-fixed': '#360b1e',
        'on-error-container': '#93000a',
        'surface-dim': '#dcdad2',
        'on-secondary-fixed': '#001f27',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#baeafa',
        'surface-container-high': '#eae8e0',
        'surface-bright': '#fbf9f1',
        'error': '#ba1a1a',
        'inverse-on-surface': '#f3f1e9',
        'surface-container-lowest': '#ffffff',
        'surface': '#fbf9f1',
        'surface-container-low': '#f5f4ec',
        'on-primary-fixed-variant': '#6a364a',
        'secondary': '#356572',
        'on-tertiary-fixed': '#002204',
        'outline-variant': '#d5c2c6',
        'on-tertiary-container': '#385e37',
        'coral-red': '#FF9B9B',
        'primary-fixed-dim': '#fab3ca',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'container-max': '1200px',
        'gutter': '16px',
        'margin-mobile': '20px',
        base: '8px',
      },
      fontFamily: {
        'body-md': ['Nunito Sans'],
        'price-display': ['Quicksand'],
        'headline-md': ['Quicksand'],
        'headline-lg-mobile': ['Quicksand'],
        'label-caps': ['Quicksand'],
        'display-hero': ['Quicksand'],
        'headline-lg': ['Quicksand'],
        'body-lg': ['Nunito Sans'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'price-display': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
